### ISSUE TITLE
How to insert a row

### ISSUE THREAD

**Issue by yq0810** [qrilka/xlsx#131]
I didn't see a similar function

**Comment by qrilka** [comment]
Hi @yq0810 
Sorry for a late reply - was away on vacation.
Could you explain what "insert a row" mean for Excel? I'm asking because a row without any cells with values makes not much sense. As for inserting cell values see e.g. https://hackage.haskell.org/package/xlsx-0.8.1/docs/Codec-Xlsx.html
Let me know if this doesn't answer your question.

**Comment by yq0810** [comment]
Like this and follow the style
![image](https://user-images.githubusercontent.com/60505593/91926136-25082200-ed09-11ea-81b6-334cb9974a61.png)

**Comment by qrilka** [comment]
It's not clear what exactly do you need - just insert numbers cells A1 to A9 and then A11 to A17.
If what you want is to move cells A10:A16 to A11:A17 and add an empty cell A10 then you need to do all of that by yourself - there's no magic instruction to do this in one go. It's like when you have C array (or Haskell vector) - you can't insert a value into middle of it moving all elements higher, you need to write some code to do that.

**Comment by qrilka** [comment]
@yq0810 were you able to resolve this already or still need some help? With no response I'll close this late today.
