### ISSUE TITLE
Problem reading fonts

### ISSUE THREAD

**Issue by vesten** [qrilka/xlsx#51]
When run over the attached Excel file, the StyleSheet returned by parseStyleSheet shows only two Font structures when the xml from ex/xl/styles.xml shows five.
[ex.xlsx](https://github.com/qrilka/xlsx/files/330903/ex.xlsx)

**Comment by qrilka** [comment]
Hi @vesten thanks for reporting this.
It looks like `xlsx` merges equal fonts from XML into 1 `Font` record.
But that could lead to errors  - e.g. in that file I see `xf` records referencing all of those 5 entries.
I'll try to look into it later this week

**Comment by vesten** [comment]
Hey @qrilka thanks for responding so quickly. If I can offer any further help diagnosing or testing, please don't hesitate to ask.

**Comment by qrilka** [comment]
For some reason value `0` (Not applicable) of font family was missing from parsing code, that was fixed by ba1da12cf69bf86e3f1fb6286238d2d1a08ca0c1
@vesten how did you create that file? I see "LibreOffice" in it's props
Spec doesn't say much about that "Not applicable" font family option and it would be interesting to find out what could it be used for.

**Comment by vesten** [comment]
Verified. The new release works great. Thanks @qrilka for taking the time to investigate and provide a fix. And to answer your question, the file was created with LibreOffice Calc (4.3.3.2, build id: 430m0(Build:2) under Debian Jessie. Upon 'Save As' I selected the xlsx format and was asked to confirm the format again via a pop-up dialog.
