### ISSUE TITLE
Three R packages cannot read the files created by xlsx

### ISSUE THREAD

**Issue by stla** [qrilka/xlsx#78]
Hello @qrilka 

 You might be interested to know that three very good R packages fail to read the files created by your library: https://github.com/nacnudus/tidyxl/issues/13 (tidyxl, openxlsx, and the current development version of readxl). 
Since these files can be opened in Excel and LibreOffice without issue, I agree that these packages should be able to read them. But perhaps you could do something to make these files more standard. Since these packages fail to read these files, we can suspect that other packages/softwares fail as well.

**Comment by qrilka** [comment]
@stla I think we have talked about using more standard namespace prefixes - I don't have any objections against it - it just means R library authors can't write XML parsing code correctly :)

**Comment by stla** [comment]
They can, since the current released version of `readxl` can read the file.
Yes, we already talked about the `vt` namespace, but actually it was an issue with the Javascript library `js-xlsx`.

**Comment by jennybc** [comment]
I assure you we R package authors understand XML parsing and namespacing.

In readxl, we wrap an external library, RapidXML, for it speed. Unfortunately, it does not genuinely support XML namespaces and we will have to patch it or workaround that some other way for xlsx that uses nonstandard namespace prefixes. Which seems to consist substantially of xlsx files written by this Haskell library. However this is not the only source and, of course, I want readxl to read everything it should. It's just a matter of prioritization.

So we are working under constraints and making compromises, not incompetent.

Unless there's a specific advantage to using nonstandard namespace prefixes, it would seem to make sense to use the same prefixes as Excel itself, since most xlsx readers will be optimized for that.

**Comment by qrilka** [comment]
@stla could you check out 0ebcc90793bd366fc374dc501d3b295027acd587 ?
It fixes only 1 prefix in only 1 file - I guess that could be enough at least for your case.
If it is then I could release this quickfix as 4.3 alongside with sheet protection which is in the master already and with upcoming fix for #77

**Comment by stla** [comment]
Hi @qrilka 
I've just tried.

- `readxl`: I didn't manage to install the development version, so I can't say (permission denied to copy a dll - the laptop of my job company has a bunch of such funny features). I'll try later, maybe I need to delete the previous version.

- `tidyxl`: no change, reading the file still crashes the R session

- `openxlsx`: it still cannot read the file, but the error message is different:
```
> openxlsx::read.xlsx("db0a04c.xlsx")
Error in read.xlsx.default("db0a04c.xlsx") : expecting a single value
```

**Comment by stla** [comment]
I finally managed to install `readxl` (perhaps I didn't need to delete the previous one, actually I had another opened session of RStudio).
*And yes, it works !!*

I will send the file to @nacnudus for `tidyxl`.

**Comment by stla** [comment]
@qrilka 
To conclude, your update is nice. The failure of `openxlsx` is not highly unfortunate, since we rather use this package for writing (`readxl` is better for reading).

**Comment by qrilka** [comment]
Closing this as resolved, if there is still something missing - pleas raise your voice
